# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-04 19:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('air', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='airport',
            name='symbol',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
